//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaguettoHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loginUser
    {
        public int idUser { get; set; }
        public string Username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string tipoUsuario { get; set; }
        public string admin { get; set; }
        public Nullable<int> foreignId { get; set; }
    }
}
