//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaguettoHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int idQuarto { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string Quarto { get; set; }
        public string valorDiaria { get; set; }
        public string valorTotal { get; set; }
        public System.DateTime dataEntrada { get; set; }
        public System.DateTime dataSaida { get; set; }

        public static explicit operator Reserva(List<Reserva> v)
        {
            throw new NotImplementedException();
        }
    }
}
