//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaguettoHotel.App_Start
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendas
    {
        public int idVendas { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string valorDiaria { get; set; }
        public string valorServicos { get; set; }
    }
}
